import { ProvenanceHeader, EpistemicBadge, AuthorshipMarker, DemoContainer } from '../components';
import ContextSageWebsite from '../artifacts/ContextSageWebsite';

export default function ContextSagePage() {
  return (
    <section aria-labelledby="context-sage-section">
      <h2 id="context-sage-section" style={{
        fontSize: '18px',
        fontWeight: '600',
        color: '#1e293b',
        margin: '0 0 16px 0',
      }}>
        Context Sage Website
      </h2>

      <ProvenanceHeader
        agent="Claude (Opus 4.5)"
        date="2026-01-02"
        context="Knowledge System documentation website"
        sourceUrl="https://github.com/adambalm/portfolio/blob/main/src/artifacts/ContextSageWebsite.jsx"
      />

      <EpistemicBadge status="ILLUSTRATIVE" />

      <AuthorshipMarker
        type="AI"
        details="Generated by Claude from Basic Memory knowledge base"
      />

      <DemoContainer title="Context Sage Documentation">
        <ContextSageWebsite />
      </DemoContainer>
    </section>
  );
}
