import { ProvenanceHeader, EpistemicBadge, AuthorshipMarker, DemoContainer } from '../components';
import MementoDemo from '../artifacts/MementoDemo';

export default function MementoPage() {
  return (
    <section aria-labelledby="memento-section">
      <h2 id="memento-section" style={{
        fontSize: '18px',
        fontWeight: '600',
        color: '#1e293b',
        margin: '0 0 16px 0',
      }}>
        Memento Demo
      </h2>

      <ProvenanceHeader
        agent="Claude (Opus 4.5)"
        date="2026-01-05"
        context="Browser session capture and classification demo"
        sourceUrl="https://github.com/adambalm/portfolio/blob/main/src/artifacts/MementoDemo.jsx"
      />

      <EpistemicBadge status="ILLUSTRATIVE" />

      <AuthorshipMarker
        type="AI"
        details="Generated by Claude from real Memento session data"
      />

      <DemoContainer title="Memento Browser Session Capture">
        <MementoDemo />
      </DemoContainer>
    </section>
  );
}
