import { ProvenanceHeader, EpistemicBadge, AuthorshipMarker, DemoContainer } from '../components';
import SkillForgeVisualizer from '../artifacts/SkillForgeVisualizer';

export default function SkillForgePage() {
  return (
    <section aria-labelledby="skill-forge-section">
      <h2 id="skill-forge-section" style={{
        fontSize: '18px',
        fontWeight: '600',
        color: '#1e293b',
        margin: '0 0 16px 0',
      }}>
        Skill Forge Visualizer
      </h2>

      <ProvenanceHeader
        agent="Claude (Opus 4.5)"
        date="2025-01-05"
        context="Skill Forge pattern educational visualization"
        sourceUrl="https://github.com/adambalm/portfolio/blob/main/src/artifacts/SkillForgeVisualizer.jsx"
      />

      <EpistemicBadge status="ILLUSTRATIVE" />

      <AuthorshipMarker
        type="AI"
        details="Generated by Claude during Skill Forge deliberation"
      />

      <DemoContainer title="Interactive Skill Forge Pattern">
        <SkillForgeVisualizer />
      </DemoContainer>
    </section>
  );
}
