/**
 * ProvenanceHeader - Displays origin information for demo content
 */
export default function ProvenanceHeader({ agent, date, context, sourceUrl }) {
  return (
    <div style={{
      backgroundColor: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '4px',
      padding: '12px 16px',
      marginBottom: '16px',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      fontSize: '13px',
      color: '#475569',
    }}>
      <div style={{ fontWeight: '600', color: '#475569', marginBottom: '4px' }}>
        Provenance
      </div>
      <div>Generated by: <strong>{agent}</strong></div>
      <div>Date: <strong>{date}</strong></div>
      <div>Context: <strong>{context}</strong></div>
      {sourceUrl && (
        <div style={{ marginTop: '8px' }}>
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#1d4ed8', textDecoration: 'underline' }}
          >
            View source artifact →
          </a>
        </div>
      )}
    </div>
  );
}
