/**
 * DemoWithBoundaries.jsx
 *
 * Evidence artifact for Skill Forge deliberation.
 * Demonstrates explicit boundary markers to prevent epistemic authority laundering.
 *
 * Boundary markers implemented:
 * 1. Provenance header - agent, date, context
 * 2. Epistemic status badge - VERIFIED, ILLUSTRATIVE, EXPLORATORY
 * 3. Authorship clarity - Human/AI/Collaborative
 * 4. Source link - inspectable origin
 * 5. Visual containment - distinct from shell
 */

import { useState } from 'react';

// Epistemic status options with visual styling
const EPISTEMIC_STATUS = {
  VERIFIED: {
    label: 'VERIFIED',
    description: 'Claims checked against sources',
    color: '#166534',
    bgColor: '#dcfce7',
  },
  ILLUSTRATIVE: {
    label: 'ILLUSTRATIVE',
    description: 'Shows capability, not making truth claims',
    color: '#1e40af',
    bgColor: '#dbeafe',
  },
  EXPLORATORY: {
    label: 'EXPLORATORY',
    description: 'Work in progress, may contain errors',
    color: '#92400e',
    bgColor: '#fef3c7',
  },
};

// Authorship types
const AUTHORSHIP = {
  HUMAN: 'Human-authored',
  AI: 'AI-generated',
  COLLABORATIVE: 'Human-AI collaborative',
};

/**
 * ProvenanceHeader - Displays origin information for the demo
 */
function ProvenanceHeader({ agent, date, context, sourceUrl }) {
  return (
    <div style={{
      backgroundColor: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '4px',
      padding: '12px 16px',
      marginBottom: '16px',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      fontSize: '13px',
      color: '#475569',
    }}>
      <div style={{ fontWeight: '600', color: '#475569', marginBottom: '4px' }}>
        Provenance
      </div>
      <div>Generated by: <strong>{agent}</strong></div>
      <div>Date: <strong>{date}</strong></div>
      <div>Context: <strong>{context}</strong></div>
      {sourceUrl && (
        <div style={{ marginTop: '8px' }}>
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#1d4ed8', textDecoration: 'underline' }}
          >
            View source artifact →
          </a>
        </div>
      )}
    </div>
  );
}

/**
 * EpistemicBadge - Visual indicator of epistemic status
 */
function EpistemicBadge({ status }) {
  const config = EPISTEMIC_STATUS[status];
  if (!config) return null;

  return (
    <div style={{
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      padding: '6px 12px',
      backgroundColor: config.bgColor,
      border: `1px solid ${config.color}`,
      borderRadius: '4px',
      marginBottom: '16px',
    }}>
      <span style={{
        fontWeight: '700',
        fontSize: '12px',
        letterSpacing: '0.05em',
        color: config.color,
      }}>
        [{config.label}]
      </span>
      <span style={{
        fontSize: '12px',
        color: '#475569',
      }}>
        {config.description}
      </span>
    </div>
  );
}

/**
 * AuthorshipMarker - Indicates who/what created the content
 */
function AuthorshipMarker({ type, details }) {
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      fontSize: '12px',
      color: '#475569',
      marginBottom: '16px',
    }}>
      <span style={{
        backgroundColor: '#e2e8f0',
        padding: '2px 8px',
        borderRadius: '4px',
        fontWeight: '500',
      }}>
        {AUTHORSHIP[type] || type}
      </span>
      {details && <span>— {details}</span>}
    </div>
  );
}

/**
 * DemoContainer - Visual containment that distinguishes demo from shell
 */
function DemoContainer({ children, title }) {
  return (
    <div style={{
      border: '2px dashed #475569',
      borderRadius: '8px',
      padding: '24px',
      backgroundColor: '#ffffff',
      position: 'relative',
      marginTop: '24px',
    }}>
      {/* Corner label indicating this is contained demo content */}
      <div style={{
        position: 'absolute',
        top: '-12px',
        left: '16px',
        backgroundColor: '#475569',
        color: '#ffffff',
        padding: '4px 12px',
        borderRadius: '4px',
        fontSize: '11px',
        fontWeight: '600',
        letterSpacing: '0.05em',
        textTransform: 'uppercase',
      }}>
        Demo Content
      </div>

      {title && (
        <h3 style={{
          margin: '8px 0 16px 0',
          fontSize: '18px',
          fontWeight: '600',
          color: '#1e293b',
        }}>
          {title}
        </h3>
      )}

      {children}
    </div>
  );
}

/**
 * SampleDemoContent - Example content to show inside the boundary
 */
function SampleDemoContent() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <p style={{ color: '#475569', lineHeight: '1.6' }}>
        This is sample demo content enclosed within explicit boundaries.
        The surrounding markers make clear:
      </p>
      <ul style={{ color: '#475569', lineHeight: '1.8', paddingLeft: '20px' }}>
        <li>Who/what generated this content</li>
        <li>When and in what context</li>
        <li>What epistemic warranty it carries</li>
        <li>That it is distinct from the containing shell</li>
      </ul>

      <div style={{ marginTop: '16px' }}>
        <button
          onClick={() => setCount(c => c + 1)}
          style={{
            backgroundColor: '#1d4ed8',
            color: 'white',
            border: 'none',
            padding: '8px 16px',
            borderRadius: '4px',
            cursor: 'pointer',
            fontSize: '14px',
          }}
          aria-label="Increment counter"
        >
          Interactive element: clicked {count} times
        </button>
      </div>
    </div>
  );
}

/**
 * DemoWithBoundaries - Main component demonstrating all boundary markers
 */
export default function DemoWithBoundaries() {
  return (
    <div style={{
      maxWidth: '800px',
      margin: '0 auto',
      padding: '32px 24px',
      fontFamily: 'system-ui, -apple-system, sans-serif',
    }}>
      {/* Shell content - visually distinct from demo */}
      <header style={{
        borderBottom: '1px solid #e2e8f0',
        paddingBottom: '24px',
        marginBottom: '24px',
      }}>
        <h1 style={{
          fontSize: '24px',
          fontWeight: '700',
          color: '#0f172a',
          margin: '0 0 8px 0',
        }}>
          Portfolio Shell
        </h1>
        <p style={{
          color: '#475569',
          margin: 0,
          fontSize: '14px',
        }}>
          This header represents the canonical portfolio shell.
          Content below is explicitly marked as a contained demonstration.
        </p>
      </header>

      {/* Boundary markers section */}
      <section aria-labelledby="demo-section">
        <h2 id="demo-section" style={{
          fontSize: '18px',
          fontWeight: '600',
          color: '#1e293b',
          margin: '0 0 16px 0',
        }}>
          Embedded Demonstration with Explicit Boundaries
        </h2>

        {/* 1. Provenance header */}
        <ProvenanceHeader
          agent="Claude Code (Opus 4.5)"
          date="2026-01-05"
          context="Skill Forge deliberation - instantiation evidence"
          sourceUrl="https://github.com/adambalm/portfolio/blob/main/dialogues/Dialogue%20-%20Portfolio%20Umbrella%20Site%20Integration.md"
        />

        {/* 2. Epistemic badge */}
        <EpistemicBadge status="ILLUSTRATIVE" />

        {/* 3. Authorship marker */}
        <AuthorshipMarker
          type="AI"
          details="Generated by Claude Code during deliberation"
        />

        {/* 4 & 5. Visual containment with demo content */}
        <DemoContainer title="Sample Interactive Component">
          <SampleDemoContent />
        </DemoContainer>
      </section>

      {/* Footer - shell content */}
      <footer style={{
        marginTop: '48px',
        paddingTop: '24px',
        borderTop: '1px solid #e2e8f0',
        fontSize: '12px',
        color: '#475569',
      }}>
        <p>
          This page demonstrates boundary markers as specified in the
          Skill Forge deliberation. The visual containment (dashed border,
          "Demo Content" label) distinguishes embedded content from the
          canonical shell.
        </p>
      </footer>
    </div>
  );
}
